enum AppErrorCodes {
  TOKEN_INVALID = 'ERROR-401-JWT',
  USER_TYPE_NON_EXISTENT = 'ERROR-401-USER-TYPE-NON-EXISTENT',
  USER_TYPE_INSUFFICIENT = 'ERROR-401-USER-TYPE-INSUFFICIENT'
}

export { AppErrorCodes }
