version: '3'

services:
  db:
    image: mariadb:latest
    ports:
      - "127.0.0.1:3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "mypass"
    command:
      - --log-bin
      - --binlog-format=MIXE
    volumes: 
      - mysql-data:/var/lib/mysql
  app:
    build: .
    ports: 
      - "3000:3000"
    depends_on: 
      - db

volumes:
  mysql-data:
