version: '3'

services:
  db:
    image: mariadb:latest
    ports:
      - "127.0.0.1:3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "mypass"
    command:
      - --log-bin
      - --binlog-format=MIXE
    volumes: 
      - mysql-data:/var/lib/mysql
    restart: always

  db-test:
    image: mariadb:latest
    ports:
      - "127.0.0.1:3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "mypass"
    command:
      - --log-bin
      - --binlog-format=MIXE
    volumes: 
      - mysql-data-test:/var/lib/mysql  
    restart: always

  redis:
    image: redis:7-alpine
    ports:
      - "127.0.0.1:6379:6379"
    # command: ["redis-server","--appendonly","yes","--requirepass","${REDIS_PASSWORD}"]
    command: ["redis-server","--appendonly","yes"]
    volumes:
      - redis-data:/data
    restart: always

  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      # - HTTP_USER=<usuario>        # opcional
      # - HTTP_PASSWORD=<senha>      # opcional
      # - REDIS_HOSTS=local:redis:6379:0:${REDIS_PASSWORD}
    ports:
      - "127.0.0.1:8081:8081"
    depends_on:
      - redis
    restart: always

volumes:
  mysql-data:
  mysql-data-test:
  redis-data:

