- hosts: private
  become: true
  vars_files:
    - ../group_vars/private.yaml
  tasks:

    - name: Instalar dependências básicas
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present
        update_cache: yes

    - name: Adicionar chave GPG oficial da Docker
      ansible.builtin.shell: |
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        chmod a+r /etc/apt/keyrings/docker.gpg
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Adicionar repositório oficial da Docker
      ansible.builtin.shell: |
        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
          $(. /etc/os-release && echo \"$VERSION_CODENAME\") stable" \
          | tee /etc/apt/sources.list.d/docker.list > /dev/null
      args:
        creates: /etc/apt/sources.list.d/docker.list

    - name: Atualizar cache do apt
      apt:
        update_cache: yes

    - name: Instalar Docker e Git
      apt:
        name:
          - docker.io
          - git
        state: present

    - name: Instalar plugin do Docker Compose
      apt:
        name: docker-compose-plugin
        state: present

    - name: Iniciar e habilitar Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Clonar repositório da aplicação
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_path }}"
        version: "{{ repo_branch }}"
        force: yes

    - name: Copiar .env do back-end do control node
      copy:
        src: "{{ backend_env_path }}"
        dest: "{{ app_path }}/source/back-end/.env"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0644

    - name: Baixar a última imagem do Docker
      command: docker compose -f docker-compose.prod.yaml pull
      args:
        chdir: "{{ app_path }}/source"

    - name: Subir containers com Docker Compose
      command: docker compose -f docker-compose.prod.yaml up -d
      args:
        chdir: "{{ app_path }}/source"

    - name: Rodar migrations do Prisma
      command: docker compose -f docker-compose.prod.yaml exec -T app npx prisma migrate deploy
      args:
        chdir: "{{ app_path }}/source"