name: Run Unit Tests

on:
  push:
    paths:
      - 'source/back-end/**'
  pull_request:
    paths:
      - 'source/back-end/**'

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        working-directory: source/back-end
        run: npm install

      - name: Run Unit Tests
        working-directory: source/back-end
        run: npm run test:unit
